version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_FORWARD_PORT}:${CLIENT_PORT}" # Mapping external port to internal port
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "${SERVER_PORT}:${SERVER_FORWARD_PORT}"
    environment:
      - DB_USERNAME=${SERVER_DB_USERNAME}
      - DB_PASSWORD=${SERVER_DB_PASSWORD}
      - DB_HOST=${SERVER_DB_HOST}
      - DB_PORT=${SERVER_DB_PORT}
      - DB_NAME=${SERVER_DB_NAME}
      - DB_CHARSET=${SERVER_DB_CHARSET}
      - DB_PARSE_TIME=${SERVER_DB_PARSE_TIME}
      - DB_LOC=${SERVER_DB_LOC}
    depends_on:
      - db

  db:
    image: mysql:8
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVER_DB_PASSWORD}
      MYSQL_DATABASE: horizon
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${SERVER_DB_USERNAME}
      - PMA_PASSWORD=${SERVER_DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
