services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_FORWARD_PORT}:${CLIENT_PORT}"
    environment:
      - CLIENT_FORWARD_PORT=${CLIENT_FORWARD_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
      - CLIENT_SERVER_URL=${CLIENT_SERVER_URL}
    depends_on:
      - server
    env_file: ./.env
    volumes:
      - ./client:/app

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./server:/app
    ports:
      - "${SERVER_PORT}:${SERVER_FORWARD_PORT}"
    environment:
      - SERVER_DB_USERNAME=${SERVER_DB_USERNAME}
      - SERVER_DB_PASSWORD=${SERVER_DB_PASSWORD}
      - SERVER_DB_HOST=${SERVER_DB_HOST}
      - SERVER_DB_PORT=${SERVER_DB_PORT}
      - SERVER_DB_NAME=${SERVER_DB_NAME}
      - SERVER_DB_CHARSET=${SERVER_DB_CHARSET}
      - SERVER_DB_PARSE_TIME=${SERVER_DB_PARSE_TIME}
      - SERVER_DB_LOC=${SERVER_DB_LOC}
      - SERVER_MINIO_ENDPOINT=${SERVER_MINIO_ENDPOINT}
      - SERVER_MINIO_REGION=${SERVER_MINIO_REGION}
      - SERVER_MINIO_ACCESS_KEY=${SERVER_MINIO_ACCESS_KEY}
      - SERVER_MINIO_SECRET_KEY=${SERVER_MINIO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: lands-horizon-db
    image: mysql:8.4
    platform: linux/amd64
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVER_DB_PASSWORD}
      MYSQL_DATABASE: ${SERVER_DB_NAME}
      MYSQL_USER: ${SERVER_DB_USERNAME}
      MYSQL_PASSWORD: ${SERVER_DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD:
    ports:
      - "${SERVER_DB_PORT}:${SERVER_DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "--user=${SERVER_DB_USERNAME}",
          "--password=${SERVER_DB_PASSWORD}",
          "--execute=SELECT 1",
        ]
      interval: 20s
      retries: 10
      start_period: 60s
      timeout: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    env_file: ./.env
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${SERVER_DB_USERNAME}
      - PMA_PASSWORD=${SERVER_DB_PASSWORD}
    depends_on:
      - db

  flyway:
    build:
      context: ./migration
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_DB_HOST: db
      SERVER_DB_PORT: ${SERVER_DB_PORT}
      SERVER_DB_USERNAME: ${SERVER_DB_USERNAME}
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}
      SERVER_DB_NAME: ${SERVER_DB_NAME}
      SERVER_DB_CHARSET: ${SERVER_DB_CHARSET}
      SERVER_DB_PARSE_TIME: ${SERVER_DB_PARSE_TIME}
    entrypoint: ["flyway", "migrate"]

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "38813:38813"
    environment:
      MINIO_ROOT_USER: ${SERVER_MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${SERVER_MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":38813"

volumes:
  db_data:
  minio_data:
