import { randomChoose } from '@/helpers'

export const startOfDayQuotes: string[] = [
    'Start your day with a positive mindset and watch the magic happen.',
    'Every morning is a fresh start. Make today amazing!',
    'Your work is a reflection of your passion. Shine bright today!',
    'Embrace the challenges today brings and grow stronger.',
    'Believe in yourself and all that you are. Have a great day!',
    'Success starts with the decision to try. Let’s make it happen today.',
    'Stay focused, stay humble, and achieve greatness.',
    'Today is a new opportunity to excel and make a difference.',
    'Your dedication today leads to success tomorrow.',
    'Rise and grind! Your efforts today shape your future.',
    'Positive thoughts lead to positive outcomes. Have a wonderful day!',
    'Take pride in how far you’ve come and have faith in how far you can go.',
    'Every step you take today is a step towards your goals.',
    'Stay motivated, stay inspired, and keep pushing forward.',
    'Let your passion drive you to new heights today.',
    'Start strong, stay strong, and finish strong.',
    "Your hard work doesn't go unnoticed. Keep it up!",
    'Embrace the day with enthusiasm and purpose.',
    'Today is a perfect day to achieve something great.',
    'Stay positive, work hard, and make it happen.',
    'Your attitude determines your direction. Stay positive!',
    "Believe you can and you're halfway there.",
    'Success is the sum of small efforts repeated day in and day out.',
    'Push yourself, because no one else is going to do it for you.',
    'The only way to do great work is to love what you do.',
    'Dream big, work hard, stay focused.',
    'Your potential is endless. Go do what you were created to do.',
    'Start each day with a grateful heart and a determined mind.',
    'Great things never come from comfort zones.',
    'Don’t watch the clock; do what it does. Keep going.',
    'The future depends on what you do today.',
    'Stay dedicated. It’s not going to happen overnight.',
    'Success doesn’t just find you. You have to go out and get it.',
    'Your work ethic is your greatest asset. Utilize it today.',
    'Wake up with determination and go to bed with satisfaction.',
    'Every morning is a chance to start anew. Make the most of it.',
    'Stay positive, work hard, and make it happen.',
    'Consistency is key. Keep pushing forward.',
    'Your effort today paves the way for tomorrow’s success.',
    'Stay focused on your goals and never give up.',
    'Every day is a new opportunity to grow and improve.',
    'Let your passion fuel your work today.',
    'Success is not for the lazy. Get up and grind!',
    'Your dedication inspires those around you. Keep it up!',
    'Start your day with a smile and positive thoughts.',
    'Make today count. Your future self will thank you.',
    'Stay resilient. Challenges are opportunities in disguise.',
    'Push beyond your limits and achieve the extraordinary.',
    'Your commitment today leads to your achievements tomorrow.',
    'Stay motivated and watch your dreams become reality.',
    'Begin each day with a clear vision and purpose.',
    'Hard work beats talent when talent doesn’t work hard.',
    'Stay hungry for success and relentless in your pursuit.',
    'Your attitude can turn a bad day into a great one.',
    'Embrace today’s challenges with confidence and strength.',
    'Let your work speak for itself. Strive for excellence.',
    'Stay proactive and make things happen today.',
    'Your perseverance today builds your legacy tomorrow.',
    'Start with a goal, stay with it, and achieve greatness.',
    'Stay inspired and inspire others through your work.',
    'Believe in your abilities and push your boundaries.',
    'Every accomplishment starts with the decision to try.',
    'Stay focused on your journey, not the destination.',
    'Your passion is your power. Use it wisely today.',
    'Rise above the ordinary and achieve the extraordinary.',
    'Stay committed to your goals, no matter the obstacles.',
    'Your positive energy can transform your day and others.',
    'Start today with a mindset of success and abundance.',
    'Keep pushing forward. Success is just around the corner.',
    'Stay enthusiastic and tackle your tasks with vigor.',
    'Your hard work is laying the foundation for your success.',
    'Begin each day with determination and end it with satisfaction.',
    'Stay organized, stay motivated, and achieve your goals.',
    'Your dedication is the key to unlocking your potential.',
    'Start your day with purpose and drive.',
    'Stay confident in your abilities and your work will shine.',
    'Every day is a new chance to excel and innovate.',
    'Stay driven and let your ambition lead the way.',
    'Your commitment today shapes your success tomorrow.',
    'Begin with a positive thought and watch your day unfold.',
    'Stay inspired, stay focused, and achieve greatness.',
    'Your effort today is the seed of tomorrow’s achievements.',
    'Start strong, stay dedicated, and finish with pride.',
    'Stay passionate about your work and success will follow.',
    'Your resilience today builds your strength for tomorrow.',
    'Begin each day with enthusiasm and determination.',
    'Stay motivated and let your success speak for itself.',
    'Your hard work and dedication are your greatest assets.',
    'Start your day with confidence and a positive attitude.',
    'Stay committed to excellence in everything you do.',
    'Your perseverance today leads to triumph tomorrow.',
    'Begin with purpose, work with passion, and achieve greatness.',
    'Stay focused, stay driven, and make your dreams a reality.',
]

export const endOfDayQuotes: string[] = [
    'Great job today! Rest well and recharge for tomorrow.',
    'Reflect on your achievements today and be proud of your progress.',
    'Every day may not be perfect, but there is something good in every day.',
    'Take a moment to appreciate what you’ve accomplished today.',
    'Your hard work today paves the way for tomorrow’s success.',
    'End your day with gratitude and a positive mindset.',
    'You did your best today. Now, give yourself permission to rest.',
    'Celebrate the small victories and learn from the challenges.',
    'Relax and unwind—you’ve earned it!',
    'Another day, another opportunity to grow. Well done!',
    'Let go of today’s worries and embrace a restful night.',
    'Your dedication today makes a difference. Thank you!',
    'Take pride in how far you’ve come and look forward to where you’re going.',
    'Rest well tonight knowing you gave your all today.',
    'End the day with a smile, knowing you made progress.',
    'You’ve handled today’s tasks with excellence. Great work!',
    'Reflect on your successes and plan for an even better tomorrow.',
    'Wind down and recharge—you deserve it.',
    'Your efforts today have not gone unnoticed. Well done!',
    'Take a deep breath and let go of the day’s stress.',
    'Each day is a step towards your goals. Keep moving forward.',
    'Thank you for your hard work and dedication today.',
    'End the day with a peaceful mind and a satisfied heart.',
    'You’ve made today productive and meaningful. Great job!',
    'Relax and enjoy your evening—you’ve earned it.',
    'Celebrate today’s accomplishments and set intentions for tomorrow.',
    'Your positive attitude today was inspiring. Thank you!',
    'Take a moment to acknowledge your hard work today.',
    'Let today’s achievements fuel your motivation for tomorrow.',
    'End the day knowing you gave your best effort.',
    'You’ve contributed significantly today. Well deserved rest!',
    'Reflect on today’s lessons and carry them forward.',
    'Unwind and recharge for a fresh start tomorrow.',
    'Your perseverance today leads to your success tomorrow.',
    'End the day with gratitude for the opportunities you had.',
    'You’ve done wonderfully today. Enjoy your evening!',
    'Take pride in today’s work and look forward to tomorrow’s challenges.',
    'Rest easy knowing you made a difference today.',
    'Celebrate your achievements, no matter how small.',
    'End the day with a heart full of gratitude and joy.',
    'You’ve accomplished a lot today. Well done!',
    'Take time to relax and rejuvenate for tomorrow.',
    'Your hard work today sets the foundation for tomorrow’s success.',
    'Reflect on your day with pride and peace.',
    'You’ve handled today’s tasks with grace and efficiency.',
    'End the day knowing you’re moving closer to your goals.',
    'Take a moment to appreciate your dedication today.',
    'Let go of today’s challenges and embrace a restful night.',
    'You’ve made meaningful progress today. Great job!',
    'Relax and recharge—you’ve earned every moment of rest.',
    'Celebrate today’s wins and learn from the day’s lessons.',
    'End the day with a positive outlook and a calm mind.',
    'Your efforts today have brought us closer to our goals.',
    'Take pride in what you’ve achieved today.',
    'Reflect on today’s successes and plan for tomorrow’s victories.',
    'You’ve worked hard today. Now, take time to unwind.',
    'End the day with a sense of accomplishment and peace.',
    'Your dedication today is appreciated. Well done!',
    'Take a deep breath and let the day’s stress fade away.',
    'Celebrate your hard work and prepare for a new day.',
    'You’ve made a difference today. Thank you!',
    'End the day knowing you’ve done your best.',
    'Take time to relax and enjoy your evening.',
    'Reflect on your day’s achievements with pride.',
    'Your commitment today sets you up for success tomorrow.',
    'End the day with gratitude for your efforts and accomplishments.',
    'You’ve handled today’s challenges with strength and resilience.',
    'Take a moment to appreciate your hard work today.',
    'Relax and recharge, knowing you’ve earned your rest.',
    'Celebrate today’s progress and look forward to tomorrow’s opportunities.',
    'End the day with a peaceful mind and a fulfilled heart.',
    'Your perseverance today is commendable. Great job!',
    'Take pride in today’s work and relax with satisfaction.',
    'Reflect on the positive moments of your day.',
    'You’ve achieved a lot today. Enjoy your evening!',
    'End the day knowing you’ve contributed meaningfully.',
    'Take time to unwind and appreciate your day’s efforts.',
    'Celebrate your successes and learn from today’s experiences.',
    'Your hard work today is paving the way for tomorrow’s achievements.',
]

export const randomStartOfDayQuoute = () => {
    return randomChoose(startOfDayQuotes)
}

export const randomEndOfDayQuoute = () => {
    return randomChoose(endOfDayQuotes)
}
