export const errorMessages: Record<number, string> = {
    400: 'Bad Request: Please check the data you provided. The request was malformed or invalid.',
    401: 'Unauthorized: You are not authenticated. Please check your credentials and try again.',
    403: 'Forbidden: You do not have the necessary permissions to access this resource.',
    404: 'Not Found: The requested resource could not be found. Please verify the URL and try again.',
    405: 'Method Not Allowed: The HTTP method used is not allowed for this resource.',
    408: 'Request Timeout: The server timed out waiting for the request. Please try again later.',
    409: 'Conflict: There was a conflict with the current state of the resource. Please resolve the conflict and try again.',
    410: 'Gone: The requested resource is no longer available on the server and no forwarding address is known.',
    413: 'Payload Too Large: The request entity is too large for the server to process.',
    414: 'URI Too Long: The request URI is too long for the server to process.',
    415: 'Unsupported Media Type: The server refuses to accept the request because the payload format is unsupported.',
    422: 'Unprocessable Entity: The server understands the request, but the data is invalid. Please check your input.',
    429: 'Too Many Requests: You have made too many requests in a short period. Please wait and try again later.',
    500: 'Internal Server Error: Something went wrong on the server. Please try again later.',
    502: 'Bad Gateway: The server received an invalid response from an upstream server.',
    503: 'Service Unavailable: The server is currently unavailable. Please try again later.',
    504: 'Gateway Timeout: The server did not receive a timely response from an upstream server.',
    501: 'Not Implemented: The server does not recognize the request method or lacks the ability to fulfill it.',
    511: 'Network Authentication Required: The client needs to authenticate to gain network access.',
}
