CREATE TABLE IF NOT EXISTS `roles` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at` DATETIME(3) DEFAULT NULL,
    `name` VARCHAR(255) UNIQUE NOT NULL,
    `description` TEXT,
    `api_key` VARCHAR(255) UNIQUE NOT NULL,
    `color` VARCHAR(255) DEFAULT NULL,
    `read_role` BOOLEAN DEFAULT FALSE,
    `write_role` BOOLEAN DEFAULT FALSE,
    `update_role` BOOLEAN DEFAULT FALSE,
    `delete_role` BOOLEAN DEFAULT FALSE,
    `read_error_details` BOOLEAN DEFAULT FALSE,
    `write_error_details` BOOLEAN DEFAULT FALSE,
    `update_error_details` BOOLEAN DEFAULT FALSE,
    `delete_error_details` BOOLEAN DEFAULT FALSE,
    `read_gender` BOOLEAN DEFAULT FALSE,
    `write_gender` BOOLEAN DEFAULT FALSE,
    `update_gender` BOOLEAN DEFAULT FALSE,
    `delete_gender` BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (`id`),
    INDEX `idx_roles_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
