CREATE TABLE IF NOT EXISTS `members` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `middle_name` VARCHAR(255),
    `permanent_address` TEXT,
    `description` TEXT,
    `birthdate` DATE NOT NULL,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `is_email_verified` BOOLEAN DEFAULT FALSE,
    `is_contact_verified` BOOLEAN DEFAULT FALSE,
    `is_skip_verification` BOOLEAN DEFAULT FALSE,
    `contact_number` VARCHAR(255) NOT NULL UNIQUE,
    `status` VARCHAR(255) DEFAULT 'Pending',
    `media_id` BIGINT UNSIGNED NULL,
    `branch_id` BIGINT UNSIGNED NULL,
    `longitude` DECIMAL(10,7) NULL,
    `latitude` DECIMAL(10,7) NULL,
    `created_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at` DATETIME(3) DEFAULT NULL,
    `role_id` BIGINT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`media_id`) REFERENCES `media`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
