export enum Operator {
  Equals = 'equals',
  NotEquals = 'not_equals',
  GreaterThan = 'greater_than',
  GreaterThanOrEqual = 'greater_than_or_equal',
  LessThan = 'less_than',
  LessThanOrEqual = 'less_than_or_equal',
  Range = 'range',
  StartsWith = 'starts_with',
  EndsWith = 'ends_with',
  Includes = 'includes',
  BooleanEquals = 'boolean_equals',
  In = 'in',
  NotIn = 'not_in',
  IsNull = 'is_null',
  IsNotNull = 'is_not_null',
}
