# .air.toml

# Config file path
root = "."
tmp_dir = "tmp"

# Watch for changes in these files
[watch]
excludes = ["tmp"]
includes = ["cmd", "internal", "pkg"]

# Build options
[build]
bin = "main"
cmd = "go build -o main ./cmd/server/main.go"
exclude = []
include = ["*.go"]

# Run options
[run]
cmd = "./main"
