import {
    LuClock8 as ClockIcon,
    LuCameraOff as CameraOffIcon,
    LuHeading1 as LuHeading1Icon,
    LuHeading2 as LuHeading2Icon,
    LuHeading3 as LuHeading3Icon,
    LuHeading4 as LuHeading4Icon,
    LuHeading5 as LuHeading5Icon,
    LuHeading6 as LuHeading6Icon,
    LuListOrdered as LuListOrderedIcon,
    LuMoveHorizontal as MoveLeftRightIcon,
    LuUndo2 as LuUndo2Icon,
    LuRedo2 as LuRedo2Icon,
    LuCalendar as CalendarIcon,
    LuCalendarCheck as CalendarCheckIcon,
    LuImage as LuImageIcon,
    LuFileX as LuFileXIcon,
    LuHardDriveUpload as LuHardDriveUploadIcon,
} from 'react-icons/lu'
import {
    BsBuildingGear as BuildingCogIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsTextParagraph as BsTextParagraphIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'
import {
    LiaUser as UserIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserShieldSolid as UserShieldIcon,
} from 'react-icons/lia'
import {
    PiPushPin as PushPinIcon,
    PiUserList as UserListIcon,
    PiBuilding as BuildingIcon,
    PiNewspaper as ReportsIcon,
    PiUsersThree as Users3Icon,
    PiPushPinSlash as PushPinSlashIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiWarningCircleFill as WarningCircleIcon,
    PiCodeBlock as PiCodeBlockIcon,
    PiTextStrikethroughLight as PiTextStrikethroughLightIcon,
    PiListBulletsBold as PiListBulletsBoldIcon,
} from 'react-icons/pi'
import {
    HiTrash as TrashIcon,
    HiOutlineSun as SunIcon,
    HiOutlineMoon as MoonIcon,
    HiOutlineCog as SettingsIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineBell as NotificationIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiAdjustmentsHorizontal as AdjustIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineQuestionMarkCircle as QuestionIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
    HiOutlineCamera as CameraIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiOutlineArrowDown as ArrowDownIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
} from 'react-icons/hi2'
import {
    AiOutlineKey as KeyIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineRotateRight as RotateRightIcon,
    AiOutlineRotateLeft as RotateLeftIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
    AiOutlineMessage as AiOutlineMessageIcon,
    AiOutlineClear as AiOutlineClearIcon,
    AiOutlineFullscreen as AiOutlineFullscreenIcon,
    AiOutlineFullscreenExit as AiOutlineFullscreenExitIcon,
} from 'react-icons/ai'
import {
    MdOutlineEmail as EmailIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlinePayments as PaymentsIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdOutlineEmail as MdOutlineEmailIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdManageAccounts as AccountSettingIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
    MdRotateLeft as MdRotateLeftIcon,
    MdRotateRight as MdRotateRightIcon,
    MdOutlineFileDownload as MdOutlineFileDownloadIcon,
    MdOutlineDraw as MdOutlineDrawIcon,
} from 'react-icons/md'
import {
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
    BsCameraFill as CameraFillIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsFillPatchMinusFill as PatchMinusIcon,
    BsFillPatchCheckFill as PatchCheckIcon,
    BsLayoutSidebarInset as SidebarLeftIcon,
    BsPatchExclamationFill as PatchExclamationIcon,
} from 'react-icons/bs'
import {
    IoReload as ReloadIcon,
    IoCheckmarkOutline as CheckIcon,
    IoRefresh as RefreshIcon,
    IoCloseOutline as CloseIcon,
    IoFootstepsOutline as FootstepsIcon,
    IoCallOutline as IoCallOutlineIcon,
    IoLocationSharp as IoLocationSharpIcon,
    IoPencilOutline as EditPencilIcon,
} from 'react-icons/io5'
import {
    RxReset as ResetIcon,
    RxEyeNone as EyeNoneIcon,
    RxDotsVertical as DotsVerticalIcon,
    RxFontItalic as ToolbarItalicIcon,
    RxTrash as RxTrashIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
} from 'react-icons/rx'
import {
    FaRegEye as EyeIcon,
    FaBold as FaBoldIcon,
    FaImage as ImageIcon,
    FaPhoneAlt as PhoneIcon,
    FaFileCsv as CsvIcon,
    FaRulerHorizontal as FaRulerHorizontalIcon,
} from 'react-icons/fa'
import {
    RiListCheck3 as TransactionListIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
} from 'react-icons/ri'
import { RxDotFilled as DotMediumIcon } from 'react-icons/rx'
import {
    GoArrowLeft as ArrowLeftIcon,
    GoDotFill as DotBigIcon,
} from 'react-icons/go'
import {
    IoIosClose as XIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosFunnel as FunnelFilledIcon,
} from 'react-icons/io'
import {
    TbClearFormatting as TbClearFormattingIcon,
    TbBlockquote as TbBlockquoteIcon,
    TbSunMoon as SunMoonIcon,
} from 'react-icons/tb'

import { CgFacebook as CgFacebookIcon } from 'react-icons/cg'

import {
    CiExport as ExportIcon,
    CiFilter as FunnelOutlineIcon,
} from 'react-icons/ci'

import { GrPowerReset as GrPowerResetIcon } from 'react-icons/gr'

import { SiGooglemaps as SiGooglemapsIcon } from 'react-icons/si'
import { VscLocation as VscLocationIcon } from 'react-icons/vsc'
import { FiCamera as FiCameraIcon } from 'react-icons/fi'

export {
    XIcon,
    CsvIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    EyeIcon,
    UserIcon,
    MoonIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    ExcelIcon,
    ResetIcon,
    ReloadIcon,
    DotBigIcon,
    CameraIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    LogoutIcon,
    ExportIcon,
    ZoomInIcon,
    AdjustIcon,
    RefreshIcon,
    LuUndo2Icon,
    LuRedo2Icon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    ReportsIcon,
    PaymentsIcon,
    PushPinIcon,
    EyeNoneIcon,
    QuestionIcon,
    SettingsIcon,
    UserListIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    CalendarIcon,
    ArrowLeftIcon,
    ArrowDownIcon,
    CameraOffIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    IoIosCodeIcon,
    DragHandleIcon,
    RotateLeftIcon,
    CameraFillIcon,
    PatchMinusIcon,
    EditPencilIcon,
    PatchCheckIcon,
    LuHeading1Icon,
    LuHeading2Icon,
    LuHeading3Icon,
    LuHeading4Icon,
    LuHeading5Icon,
    LuHeading6Icon,
    EmailCheckIcon,
    CameraFlipIcon,
    UserShieldIcon,
    ChevronLeftIcon,
    RotateRightIcon,
    BuildingCogIcon,
    PiCodeBlockIcon,
    ArrowUpDownIcon,
    ChevronsLeftIcon,
    SidebarLeftIcon,
    PhoneOutlineIcon,
    FlipVerticalIcon,
    TbBlockquoteIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    NotificationIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    LuListOrderedIcon,
    FunnelOutlineIcon,
    MoveLeftRightIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    FlipHorizontalIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    MixerHorizontalIcon,
    AccountSettingIcon,
    BsTextParagraphIcon,
    TransactionListIcon,
    PatchExclamationIcon,
    FlipVerticalLineIcon,
    FaRulerHorizontalIcon,
    TbClearFormattingIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    CgFacebookIcon,
    PiTextStrikethroughLightIcon,
    PiListBulletsBoldIcon,
    AiOutlineMessageIcon,
    MdOutlineEmailIcon,
    IoCallOutlineIcon,
    IoLocationSharpIcon,
    SiGooglemapsIcon,
    VscLocationIcon,
    GrPowerResetIcon,
    MdRotateRightIcon,
    MdRotateLeftIcon,
    RxTrashIcon,
    LuImageIcon,
    LuFileXIcon,
    MdOutlineFileDownloadIcon,
    FiCameraIcon,
    LuHardDriveUploadIcon,
    MdOutlineDrawIcon,
    AiOutlineClearIcon,
    AiOutlineFullscreenIcon,
    AiOutlineFullscreenExitIcon,
}
