import {
    TbSunMoon as SunMoonIcon,
    TbBlockquote as BlockQuoteIcon,
} from 'react-icons/tb'

import {
    CiExport as ExportIcon,
    CiFilter as FunnelOutlineIcon,
} from 'react-icons/ci'

import {
    GoDotFill as DotBigIcon,
    GoArrowLeft as ArrowLeftIcon,
    GoSearch as MagnifyingGlassIcon,
} from 'react-icons/go'

import {
    IoIosClose as XIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosFunnel as FunnelFilledIcon,
} from 'react-icons/io'

import {
    LuUndo2 as UndoIcon,
    LuRedo2 as RedoIcon,
    LuTrash as TrashIcon,
    LuImage as ImageIcon,
    LuFileX as FileXIcon,
    LuClock8 as ClockIcon,
    LuCalendar as CalendarIcon,
    LuCameraOff as CameraOffIcon,
    LuListOrdered as ListOrderedIcon,
    LuCalendarCheck as CalendarCheckIcon,
    LuChevronsUpDown as ChevronsUpDownIcon,
    LuHardDriveUpload as HardDriveUploadIcon,
} from 'react-icons/lu'

import {
    BsBuildingGear as BuildingCogIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'

import {
    LiaUser as UserIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserShieldSolid as UserShieldIcon,
} from 'react-icons/lia'

import {
    PiPushPin as PushPinIcon,
    PiUserList as UserListIcon,
    PiBuilding as BuildingIcon,
    PiNewspaper as ReportsIcon,
    PiUsersThree as Users3Icon,
    PiCodeBlock as CodeBlockIcon,
    PiPushPinSlash as PushPinSlashIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiListBulletsBold as ListBulletsBoldIcon,
    PiWarningCircleFill as WarningCircleIcon,
    PiTextStrikethroughLight as TextStrikethroughLightIcon,
} from 'react-icons/pi'

import {
    HiOutlineSun as SunIcon,
    HiOutlineMoon as MoonIcon,
    HiOutlineCog as SettingsIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiOutlineBell as NotificationIcon,
    HiOutlineArrowDown as ArrowDownIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiAdjustmentsHorizontal as AdjustIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineQuestionMarkCircle as QuestionIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
} from 'react-icons/hi2'

import {
    AiOutlineKey as KeyIcon,
    AiFillHome as HomeFillIcon,
    AiOutlineClear as SmallBrushIcon,
    AiOutlineFullscreen as FullscreenIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineMessage as MessageOutlineIcon,
    AiOutlineRotateLeft as RotateBoxLeftIcon,
    AiOutlineRotateRight as RotateBoxRightIcon,
    AiOutlineFullscreenExit as FullscreenExitIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
} from 'react-icons/ai'

import {
    MdOutlineDraw as DrawIcon,
    MdOutlineEmail as EmailIcon,
    MdRotateLeft as RotateLeftIcon,
    MdRotateRight as RotateRightIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlinePayments as PaymentsIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdManageAccounts as AccountSettingIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
} from 'react-icons/md'

import {
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
    BsCameraFill as CameraFillIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsPatchQuestion as BadgeQuestionIcon,
    BsPatchQuestionFill as BadgeQuestionFillIcon,
    BsPatchMinusFill as BadgeMinusIcon,
    BsFillPatchMinusFill as BadgeMinusFillIcon,
    BsPatchCheckFill as BadgeCheckIcon,
    BsFillPatchCheckFill as BadgeCheckFillIcon,
    BsLayoutSidebarInset as SidebarLeftIcon,
    BsDashSquareDotted as DashSquareDottedIcon,
    BsPatchExclamation as BadgeExclamationIcon,
    BsPatchExclamationFill as BadgeExclamationFillIcon,
    BsFillQuestionCircleFill as QuestionCircleFillIcon,
} from 'react-icons/bs'

import {
    IoReload as ReloadIcon,
    IoRefresh as RefreshIcon,
    IoStorefront as StoreIcon,
    IoCloseOutline as CloseIcon,
    IoCallOutline as TelephoneIcon,
    IoCheckmarkOutline as CheckIcon,
    IoPencilOutline as EditPencilIcon,
    IoLocationSharp as LocationPinIcon,
    IoFootstepsOutline as FootstepsIcon,
} from 'react-icons/io5'

import {
    RxReset as ResetIcon,
    RxEyeNone as EyeNoneIcon,
    RxFontItalic as ToolbarItalicIcon,
    RxDotsVertical as DotsVerticalIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
} from 'react-icons/rx'

import {
    FaRegEye as EyeIcon,
    FaBold as FaBoldIcon,
    FaPhoneAlt as PhoneIcon,
    FaFileCsv as CsvIcon,
} from 'react-icons/fa'

import {
    RiListCheck3 as TransactionListIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
} from 'react-icons/ri'

import { FiCamera as CameraIcon } from 'react-icons/fi'

import { CgFacebook as FacebookIcon } from 'react-icons/cg'

import { RxDotFilled as DotMediumIcon } from 'react-icons/rx'

import { GrPowerReset as PowerResetIcon } from 'react-icons/gr'

import { VscLocation as LocationPinOutlineIcon } from 'react-icons/vsc'

export {
    XIcon,
    CsvIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    EyeIcon,
    UndoIcon,
    RedoIcon,
    UserIcon,
    MoonIcon,
    DrawIcon,
    FileXIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    ExcelIcon,
    StoreIcon,
    ResetIcon,
    ReloadIcon,
    DotBigIcon,
    CameraIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    LogoutIcon,
    ExportIcon,
    ZoomInIcon,
    AdjustIcon,
    RefreshIcon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    ReportsIcon,
    PushPinIcon,
    EyeNoneIcon,
    PaymentsIcon,
    HomeFillIcon,
    FacebookIcon,
    QuestionIcon,
    SettingsIcon,
    UserListIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    CalendarIcon,
    CodeBlockIcon,
    ArrowLeftIcon,
    ArrowDownIcon,
    CameraOffIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    IoIosCodeIcon,
    TelephoneIcon,
    SmallBrushIcon,
    FullscreenIcon,
    RotateLeftIcon,
    PowerResetIcon,
    BlockQuoteIcon,
    DragHandleIcon,
    CameraFillIcon,
    EditPencilIcon,
    BadgeMinusIcon,
    BadgeCheckIcon,
    EmailCheckIcon,
    CameraFlipIcon,
    UserShieldIcon,
    ArrowUpDownIcon,
    ChevronLeftIcon,
    SidebarLeftIcon,
    BuildingCogIcon,
    ListOrderedIcon,
    RotateRightIcon,
    LocationPinIcon,
    NotificationIcon,
    ChevronsLeftIcon,
    PhoneOutlineIcon,
    FlipVerticalIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    BadgeQuestionIcon,
    RotateBoxLeftIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    FunnelOutlineIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    FlipHorizontalIcon,
    RotateBoxRightIcon,
    BadgeCheckFillIcon,
    BadgeMinusFillIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    ChevronsUpDownIcon,
    AccountSettingIcon,
    FullscreenExitIcon,
    MessageOutlineIcon,
    MagnifyingGlassIcon,
    HardDriveUploadIcon,
    ListBulletsBoldIcon,
    MixerHorizontalIcon,
    TransactionListIcon,
    DashSquareDottedIcon,
    FlipVerticalLineIcon,
    BadgeExclamationIcon,
    BadgeQuestionFillIcon,
    LocationPinOutlineIcon,
    QuestionCircleFillIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    BadgeExclamationFillIcon,
    TextStrikethroughLightIcon,
}
