import {
    TbMinus as MinusIcon,
    TbSunMoon as SunMoonIcon,
    TbMoneybag as MoneyBagIcon,
    TbBlockquote as BlockQuoteIcon,
    TbHeartHandshake as HandShakeHeartIcon,
    TbSquareF1 as F1Icon,
    TbSquareF2 as F2Icon,
    TbSquareF3 as F3Icon,
} from 'react-icons/tb'

import {
    CiExport as ExportIcon,
    CiFilter as FunnelOutlineIcon,
} from 'react-icons/ci'

import {
    GoDotFill as DotBigIcon,
    GoArrowLeft as ArrowLeftIcon,
    GoSearch as MagnifyingGlassIcon,
} from 'react-icons/go'

import {
    IoIosClose as XIcon,
    IoIosCode as IoIosCodeIcon,
    IoIosFunnel as FunnelFilledIcon,
} from 'react-icons/io'

import {
    LuCopy as CopyIcon,
    LuUndo2 as UndoIcon,
    LuRedo2 as RedoIcon,
    LuTrash as TrashIcon,
    LuImage as ImageIcon,
    LuFileX as FileXIcon,
    LuClock8 as ClockIcon,
    LuQrCode as QrCodeIcon,
    LuCalendar as CalendarIcon,
    LuCameraOff as CameraOffIcon,
    LuListOrdered as ListOrderedIcon,
    LuCalendarCheck as CalendarCheckIcon,
    LuExternalLink as OpenExternalLinkIcon,
    LuChevronsUpDown as ChevronsUpDownIcon,
    LuHardDriveUpload as HardDriveUploadIcon,
    LuReplace as ReplaceIcon,
} from 'react-icons/lu'

import {
    BsBuildingGear as BuildingCogIcon,
    BsLayoutSidebarInset as SidebarIcon,
    BsLayoutSidebarInsetReverse as SidebarRightIcon,
} from 'react-icons/bs'

import {
    LiaUser as UserIcon,
    LiaUserTagSolid as UserTagIcon,
    LiaUserCogSolid as UserCogIcon,
    LiaShieldAltSolid as ShieldIcon,
    LiaUserClockSolid as UserClockIcon,
    LiaUserShieldSolid as UserShieldIcon,
    LiaMapMarkedAltSolid as MapMarkedIcon,
} from 'react-icons/lia'

import {
    PiPlus as PlusIcon,
    PiEmpty as EmptyIcon,
    PiPushPin as PushPinIcon,
    PiUserList as UserListIcon,
    PiBuilding as BuildingIcon,
    PiNewspaper as ReportsIcon,
    PiUsersThree as Users3Icon,
    PiCodeBlock as CodeBlockIcon,
    PiNotepadDuotone as NoteIcon,
    PiWarningFill as WarningFillIcon,
    PiBankDuotone as BankDuoToneIcon,
    PiPushPinSlash as PushPinSlashIcon,
    PiHandCoinsDuotone as HandCoinsIcon,
    PiMicrosoftExcelLogoFill as ExcelIcon,
    PiHeartBreakFill as HeartBreakFillIcon,
    PiSignatureLight as SignatureLightIcon,
    PiBuildingOffice as BuildingBranchIcon,
    PiHandDepositDuotone as HandDepositIcon,
    PiListBulletsBold as ListBulletsBoldIcon,
    PiGraduationCapFill as GraduationCapIcon,
    PiWarningCircleFill as WarningCircleIcon,
    PiHandWithdrawDuotone as HandWithdrawIcon,
    PiTextStrikethroughLight as TextStrikethroughLightIcon,
} from 'react-icons/pi'

import {
    HiOutlineSun as SunIcon,
    HiOutlineMoon as MoonIcon,
    HiFolder as FolderFillIcon,
    HiPencil as PencilFillIcon,
    HiOutlineCog as SettingsIcon,
    HiOutlineCodeBracket as DevIcon,
    HiOutlineArrowUp as ArrowUpIcon,
    HiOutlineBell as NotificationIcon,
    HiOutlineBriefcase as BriefCaseIcon,
    HiOutlineArrowDown as ArrowDownIcon,
    HiOutlinePencil as PencilOutlineIcon,
    HiOutlineSquaresPlus as DashboardIcon,
    HiAdjustmentsHorizontal as AdjustIcon,
    HiOutlineChevronDown as ChevronDownIcon,
    HiOutlineChevronLeft as ChevronLeftIcon,
    HiOutlineArrowsUpDown as ArrowUpDownIcon,
    HiOutlineChevronRight as ChevronRightIcon,
    HiOutlineQuestionMarkCircle as QuestionIcon,
    HiOutlineChatBubbleOvalLeft as MessagesIcon,
    HiOutlineChevronDoubleLeft as ChevronsLeftIcon,
    HiOutlineArrowRightEndOnRectangle as LogoutIcon,
    HiOutlineChevronDoubleRight as ChevronsRightIcon,
    HiOutlineChatBubbleBottomCenterText as FeedbackIcon,
} from 'react-icons/hi2'

import {
    AiOutlineKey as KeyIcon,
    AiFillHome as HomeFillIcon,
    AiOutlineClear as SmallBrushIcon,
    AiOutlineFullscreen as FullscreenIcon,
    AiOutlineLoading as LoadingCircleIcon,
    AiOutlineMessage as MessageOutlineIcon,
    AiOutlineRotateLeft as RotateBoxLeftIcon,
    AiOutlineRotateRight as RotateBoxRightIcon,
    AiOutlineFullscreenExit as FullscreenExitIcon,
    AiOutlineLoading3Quarters as LoadingSpinnerIcon,
} from 'react-icons/ai'

import {
    MdOutlineDraw as DrawIcon,
    MdOutlineEmail as EmailIcon,
    MdFamilyRestroom as FamilyIcon,
    MdRotateLeft as RotateLeftIcon,
    MdRotateRight as RotateRightIcon,
    MdMarkEmailRead as EmailCheckIcon,
    MdOutlineGroupAdd as UsersAddIcon,
    MdOutlinePayments as PaymentsIcon,
    MdOutlineAccountBalance as BankIcon,
    MdCameraEnhance as CameraSelectIcon,
    MdFlipCameraAndroid as CameraFlipIcon,
    MdManageAccounts as AccountSettingIcon,
    MdOutlineLocalPhone as PhoneOutlineIcon,
    MdOutlineRotate90DegreesCw as Rotate90DegreeRightIcon,
    MdOutlineRotate90DegreesCcw as Rotate90DegreeLeftIcon,
    MdAccountBalance as AccountsIcon,
    MdOutlineSavings as SavingsIcon,
} from 'react-icons/md'

import {
    BsImage as Image2Icon,
    BsZoomIn as ZoomInIcon,
    BsZoomOut as ZoomOutIcon,
    BsCameraFill as CameraFillIcon,
    BsPatchCheck as VerifiedPatchIcon,
    BsFileEarmarkFill as FileFillIcon,
    BsPatchQuestion as BadgeQuestionIcon,
    BsFileEarmarkPdfFill as PDFFileFillIcon,
    BsFileEarmarkTextFill as TextFileFillIcon,
    BsFileEarmarkPlayFill as VideoFileFillIcon,
    BsFileEarmarkMusicFill as MusicFileFillIcon,
    BsFileEarmarkImageFill as ImageFileFillIcon,
    BsFileEarmarkExcelFill as ExcelFileFillIcon,
    BsFileEarmarkWordFill as DocumentFileFillIcon,
    BsFileEarmarkSpreadsheetFill as SpreadSheetFileIcon,
    BsPatchQuestionFill as BadgeQuestionFillIcon,
    BsPatchMinusFill as BadgeMinusIcon,
    BsFillPatchMinusFill as BadgeMinusFillIcon,
    BsPatchCheckFill as BadgeCheckIcon,
    BsFillPatchCheckFill as BadgeCheckFillIcon,
    BsLayoutSidebarInset as SidebarLeftIcon,
    BsDashSquareDotted as DashSquareDottedIcon,
    BsPatchExclamation as BadgeExclamationIcon,
    BsPatchExclamationFill as BadgeExclamationFillIcon,
    BsFillQuestionCircleFill as QuestionCircleFillIcon,
} from 'react-icons/bs'

import {
    IoReload as ReloadIcon,
    IoRefresh as RefreshIcon,
    IoStorefront as StoreIcon,
    IoCloseOutline as CloseIcon,
    IoCallOutline as TelephoneIcon,
    IoCheckmarkOutline as CheckIcon,
    IoPencilOutline as EditPencilIcon,
    IoLocationSharp as LocationPinIcon,
    IoFootstepsOutline as FootstepsIcon,
    IoReceiptOutline as ReceiptIcon,
    IoPrintOutline as PrinterIcon,
} from 'react-icons/io5'

import {
    RxReset as ResetIcon,
    RxEyeNone as EyeNoneIcon,
    RxFontItalic as ToolbarItalicIcon,
    RxDotsVertical as DotsVerticalIcon,
    RxDragHandleDots2 as DragHandleIcon,
    RxMixerHorizontal as MixerHorizontalIcon,
} from 'react-icons/rx'

import {
    FaRegMap as MapIcon,
    FaRegEye as EyeIcon,
    FaBold as FaBoldIcon,
    FaFileCsv as CsvIcon,
    FaPhoneAlt as PhoneIcon,
    FaMoneyBill as BillIcon,
    FaCreditCard as CreditCardIcon,
    FaUserClock as UserClockFillIcon,
} from 'react-icons/fa'

import {
    FaVenusMars as GendersIcon,
    FaChartPie as PieChartIcon,
    FaBoxesStacked as BoxesStackedIcon,
    FaAddressCard as AddressCardIcon,
} from 'react-icons/fa6'

import {
    RiListCheck3 as TransactionListIcon,
    RiFlipVerticalFill as FlipVerticalIcon,
    RiFlipVerticalLine as FlipVerticalLineIcon,
    RiFlipHorizontalFill as FlipHorizontalIcon,
    RiFlipHorizontalLine as FlipHorizontalLineIcon,
} from 'react-icons/ri'

import {
    FiCamera as CameraIcon,
    FiDownload as DownloadIcon,
} from 'react-icons/fi'

import {
    GiWallet as WalletIcon,
    GiTakeMyMoney as MoneyIcon,
} from 'react-icons/gi'

import {
    CgFacebook as FacebookIcon,
    CgDetailsLess as DetailsIcon,
} from 'react-icons/cg'

import { RxDotFilled as DotMediumIcon } from 'react-icons/rx'

import { GrPowerReset as PowerResetIcon } from 'react-icons/gr'

import {
    VscError as ErrorIcon,
    VscCommentDraft as CommentDashedIcon,
    VscLocation as LocationPinOutlineIcon,
} from 'react-icons/vsc'

import { BiErrorCircle as WarningIcon } from 'react-icons/bi'

import { SlOptions as OptionsIcon } from 'react-icons/sl'

import {
    GrMoney as CoinsStackIcon,
    GrVmMaintenance as MaintenanceIcon,
} from 'react-icons/gr'
export {
    XIcon,
    MapIcon,
    CsvIcon,
    SunIcon,
    KeyIcon,
    DevIcon,
    EyeIcon,
    NoteIcon,
    CopyIcon,
    BankIcon,
    PlusIcon,
    BillIcon,
    UndoIcon,
    RedoIcon,
    UserIcon,
    MoonIcon,
    DrawIcon,
    MoneyIcon,
    EmptyIcon,
    MinusIcon,
    ErrorIcon,
    FileXIcon,
    TrashIcon,
    ClockIcon,
    CloseIcon,
    EmailIcon,
    ImageIcon,
    CheckIcon,
    PhoneIcon,
    ExcelIcon,
    StoreIcon,
    ResetIcon,
    FamilyIcon,
    ReloadIcon,
    QrCodeIcon,
    DotBigIcon,
    CameraIcon,
    FaBoldIcon,
    ShieldIcon,
    Users3Icon,
    LogoutIcon,
    ExportIcon,
    ZoomInIcon,
    AdjustIcon,
    WalletIcon,
    Image2Icon,
    DetailsIcon,
    ReplaceIcon,
    WarningIcon,
    OptionsIcon,
    UserCogIcon,
    GendersIcon,
    RefreshIcon,
    ArrowUpIcon,
    SidebarIcon,
    SunMoonIcon,
    ZoomOutIcon,
    ReportsIcon,
    PushPinIcon,
    EyeNoneIcon,
    UserTagIcon,
    PieChartIcon,
    AccountsIcon,
    PaymentsIcon,
    HomeFillIcon,
    FacebookIcon,
    QuestionIcon,
    SettingsIcon,
    UserListIcon,
    MessagesIcon,
    FeedbackIcon,
    BuildingIcon,
    DownloadIcon,
    CalendarIcon,
    FileFillIcon,
    UsersAddIcon,
    MoneyBagIcon,
    HandCoinsIcon,
    MapMarkedIcon,
    CodeBlockIcon,
    ArrowLeftIcon,
    BriefCaseIcon,
    ArrowDownIcon,
    CameraOffIcon,
    DotMediumIcon,
    FootstepsIcon,
    UserClockIcon,
    DashboardIcon,
    IoIosCodeIcon,
    TelephoneIcon,
    FolderFillIcon,
    CoinsStackIcon,
    PencilFillIcon,
    SmallBrushIcon,
    FullscreenIcon,
    RotateLeftIcon,
    PowerResetIcon,
    BlockQuoteIcon,
    DragHandleIcon,
    CameraFillIcon,
    EditPencilIcon,
    BadgeMinusIcon,
    BadgeCheckIcon,
    EmailCheckIcon,
    CameraFlipIcon,
    CreditCardIcon,
    UserShieldIcon,
    WarningFillIcon,
    AddressCardIcon,
    ArrowUpDownIcon,
    ChevronLeftIcon,
    SidebarLeftIcon,
    BuildingCogIcon,
    ListOrderedIcon,
    RotateRightIcon,
    LocationPinIcon,
    HandDepositIcon,
    ChevronDownIcon,
    PDFFileFillIcon,
    BankDuoToneIcon,
    BoxesStackedIcon,
    NotificationIcon,
    ChevronsLeftIcon,
    TextFileFillIcon,
    PhoneOutlineIcon,
    FlipVerticalIcon,
    FunnelFilledIcon,
    PushPinSlashIcon,
    DotsVerticalIcon,
    ChevronRightIcon,
    CameraSelectIcon,
    SidebarRightIcon,
    HandWithdrawIcon,
    BadgeQuestionIcon,
    VideoFileFillIcon,
    MusicFileFillIcon,
    ImageFileFillIcon,
    ExcelFileFillIcon,
    GraduationCapIcon,
    RotateBoxLeftIcon,
    ToolbarItalicIcon,
    ChevronsRightIcon,
    FunnelOutlineIcon,
    CalendarCheckIcon,
    WarningCircleIcon,
    VerifiedPatchIcon,
    LoadingCircleIcon,
    PencilOutlineIcon,
    UserClockFillIcon,
    CommentDashedIcon,
    SignatureLightIcon,
    HandShakeHeartIcon,
    FlipHorizontalIcon,
    RotateBoxRightIcon,
    BadgeCheckFillIcon,
    BadgeMinusFillIcon,
    BuildingBranchIcon,
    LoadingSpinnerIcon,
    ChevronsUpDownIcon,
    AccountSettingIcon,
    FullscreenExitIcon,
    MessageOutlineIcon,
    HeartBreakFillIcon,
    MagnifyingGlassIcon,
    SpreadSheetFileIcon,
    HardDriveUploadIcon,
    ListBulletsBoldIcon,
    MixerHorizontalIcon,
    TransactionListIcon,
    DashSquareDottedIcon,
    OpenExternalLinkIcon,
    FlipVerticalLineIcon,
    BadgeExclamationIcon,
    DocumentFileFillIcon,
    BadgeQuestionFillIcon,
    LocationPinOutlineIcon,
    QuestionCircleFillIcon,
    FlipHorizontalLineIcon,
    Rotate90DegreeLeftIcon,
    Rotate90DegreeRightIcon,
    BadgeExclamationFillIcon,
    TextStrikethroughLightIcon,
    SavingsIcon,
    ReceiptIcon,
    PrinterIcon,
    F1Icon,
    F2Icon,
    F3Icon,
    MaintenanceIcon,
}
