import {
    IAccountingLedgerResource,
    TransactionSource,
} from '@/server/types/accounts/accounting-ledger'

export const sampleLedgerData: IAccountingLedgerResource[] = [
    {
        id: 'ledger-001',
        description: 'Loan Repayment',
        notes: 'Monthly loan repayment for January',
        company_id: 'comp-001',
        member_profile_id: 'member-002',
        account_id: 'acct-002',
        employee_id: 'emp-002',
        or_number: 'OR-789012',
        transaction_source: TransactionSource.payment,
        debit: 300.0,
        credit: 0.0,
        balance: 4700.0,
        transaction_date: new Date('2024-02-20'),
        entry_date: new Date('2024-02-21'),
        line_number: 2,
        transaction_type_id: 'trans-002',
        created_by: 'admin-002',
        created_at: new Date('2024-02-21'),
        createdAt: new Date('2024-02-21').toISOString(),
        updatedAt: new Date('2024-02-21').toISOString(),
    },
    {
        id: 'ledger-002',
        description: 'Service Income',
        notes: 'Consulting services for February',
        company_id: 'comp-001',
        member_profile_id: 'member-003',
        account_id: 'acct-003',
        employee_id: 'emp-001',
        or_number: 'OR-789013',
        transaction_source: TransactionSource.withdrawal,
        debit: 0.0,
        credit: 1500.0,
        balance: 6200.0,
        transaction_date: new Date('2024-02-22'),
        entry_date: new Date('2024-02-23'),
        line_number: 3,
        transaction_type_id: 'trans-003',
        created_by: 'admin-003',
        created_at: new Date('2024-02-23'),
        createdAt: new Date('2024-02-23').toISOString(),
        updatedAt: new Date('2024-02-23').toISOString(),
    },
    {
        id: 'ledger-003',
        description: 'Equipment Purchase',
        notes: 'Laptop purchase for new employee',
        company_id: 'comp-002',
        member_profile_id: 'member-001',
        account_id: 'acct-001',
        employee_id: 'emp-003',
        or_number: 'OR-789014',
        transaction_source: TransactionSource.payment,
        debit: 1200.0,
        credit: 0.0,
        balance: 5000.0,
        transaction_date: new Date('2024-02-24'),
        entry_date: new Date('2024-02-25'),
        line_number: 4,
        transaction_type_id: 'trans-004',
        created_by: 'admin-001',
        created_at: new Date('2024-02-25'),
        createdAt: new Date('2024-02-25').toISOString(),
        updatedAt: new Date('2024-02-25').toISOString(),
    },
    {
        id: 'ledger-004',
        description: 'Utilities Payment',
        notes: 'Electricity bill for February',
        company_id: 'comp-003',
        member_profile_id: 'member-004',
        account_id: 'acct-004',
        employee_id: 'emp-004',
        or_number: 'OR-789015',
        transaction_source: TransactionSource.payment,
        debit: 400.0,
        credit: 0.0,
        balance: 4600.0,
        transaction_date: new Date('2024-02-26'),
        entry_date: new Date('2024-02-27'),
        line_number: 5,
        transaction_type_id: 'trans-005',
        created_by: 'admin-004',
        created_at: new Date('2024-02-27'),
        createdAt: new Date('2024-02-27').toISOString(),
        updatedAt: new Date('2024-02-27').toISOString(),
    },
    {
        id: 'ledger-005',
        description: 'Interest Income',
        notes: 'Savings account interest for February',
        company_id: 'comp-001',
        member_profile_id: 'member-005',
        account_id: 'acct-005',
        employee_id: 'emp-005',
        or_number: 'OR-789016',
        transaction_source: TransactionSource.deposit,
        debit: 0.0,
        credit: 200.0,
        balance: 4800.0,
        transaction_date: new Date('2024-02-28'),
        entry_date: new Date('2024-02-29'),
        line_number: 6,
        transaction_type_id: 'trans-006',
        created_by: 'admin-005',
        created_at: new Date('2024-02-29'),
        createdAt: new Date('2024-02-29').toISOString(),
        updatedAt: new Date('2024-02-29').toISOString(),
    },
]
