name: Horizon Server

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the stack
        run: |
          docker compose up --build -d
        env:
          CLIENT_PORT: 80
          CLIENT_HOST: localhost
          CLIENT_FORWARD_PORT: 8090
          SERVER_PORT: 8080
          SERVER_HOST: localhost
          SERVER_FORWARD_PORT: 8080
          SERVER_DB_USERNAME: root
          SERVER_DB_PASSWORD: root
          SERVER_DB_HOST: 127.0.0.1
          SERVER_DB_PORT: 3306
          SERVER_DB_NAME: horizon
          SERVER_DB_CHARSET: utf8
          SERVER_DB_PARSE_TIME: True
          SERVER_DB_LOC: Local
