name: Horizon Server

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo "SERVER_DB_PASSWORD=${{ secrets.SERVER_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "SERVER_DB_NAME=${{ secrets.SERVER_DB_NAME }}" >> $GITHUB_ENV
          echo "SERVER_DB_USERNAME=${{ secrets.SERVER_DB_USERNAME }}" >> $GITHUB_ENV
          echo "SERVER_DB_PORT=${{ secrets.SERVER_DB_PORT }}" >> $GITHUB_ENV
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> $GITHUB_ENV
          echo "SERVER_FORWARD_PORT=${{ secrets.SERVER_FORWARD_PORT }}" >> $GITHUB_ENV
          echo "CLIENT_FORWARD_PORT=${{ secrets.CLIENT_FORWARD_PORT }}" >> $GITHUB_ENV
          echo "CLIENT_PORT=${{ secrets.CLIENT_PORT }}" >> $GITHUB_ENV
          echo "SERVER_DB_HOST=${{ secrets.SERVER_DB_HOST }}" >> $GITHUB_ENV
          echo "SERVER_DB_CHARSET=${{ secrets.SERVER_DB_CHARSET }}" >> $GITHUB_ENV
          echo "SERVER_DB_PARSE_TIME=${{ secrets.SERVER_DB_PARSE_TIME }}" >> $GITHUB_ENV
          echo "SERVER_DB_LOC=${{ secrets.SERVER_DB_LOC }}" >> $GITHUB_ENV

      - name: Build the stack
        run: docker compose up --build -d
