name: Frontend Quality Checks Pipeline

on:
    push:
        branches:
            - main
            - development
            - staging
    pull_request:
        branches:
            - main
            - development
            - staging

jobs:
    lint:
        name: Lint Code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Install dependencies
              run: pnpm install
              working-directory: ./client

            - name: Run ESLint
              run: pnpm run lint
              working-directory: ./client

            - name: Run Prettier Check
              run: pnpm run fc
              working-directory: ./client

    test:
        name: Run Vitest Tests
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Install dependencies
              run: pnpm install
              working-directory: ./client

            - name: Run Vitest tests
              run: pnpm run test
              working-directory: ./client

    build:
        name: Build Project
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Install dependencies
              run: pnpm install
              working-directory: ./client

            - name: Run TypeScript Build
              run: pnpm run build
              working-directory: ./client

            - name: Run Vite Build
              run: pnpm run build
              working-directory: ./client
