name: Deploy Pipeline

on:
    workflow_run:
        workflows: ["Frontend Quality Checks Pipeline"]
        types:
            - completed
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_AMPLIFY_WEB_HOOK_ID: ${{ secrets.AWS_AMPLIFY_WEB_HOOK_ID }}
            AWS_AMPLIFY_WEB_HOOK_TOKEN: ${{ secrets.AWS_AMPLIFY_WEB_HOOK_TOKEN }}
        steps:
            - name: Trigger Amplify Ci Build
              run: |
                  curl -X POST -d {} "https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=$AWS_AMPLIFY_WEB_HOOK_ID&token=$AWS_AMPLIFY_WEB_HOOK_TOKEN&operation=startbuild" -H "Content-Type:application/json"
