name: Frontend Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Lint Code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Navigate to client directory
              run: cd ./client

            - name: Install dependencies using pnpm
              run: pnpm install
              working-directory: ./client

            - name: Run ESLint
              run: pnpm run lint
              working-directory: ./client

            - name: Run Prettier Check
              run: pnpm run fc
              working-directory: ./client

    test:
        name: Run Vitest Tests
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Navigate to client directory
              run: cd ./client

            - name: Install dependencies using pnpm
              run: pnpm install
              working-directory: ./client

            - name: Run Vitest tests
              run: pnpm run test
              working-directory: ./client

    build:
        name: Build Project
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.11.0"

            - name: Install pnpm
              run: npm install -g pnpm@9.14.3

            - name: Navigate to client directory
              run: cd ./client

            - name: Install dependencies using pnpm
              run: pnpm install
              working-directory: ./client

            - name: Run TypeScript Build
              run: pnpm run build
              working-directory: ./client

            - name: Run Vite Build
              run: pnpm run build
              working-directory: ./client

    deploy:
        name: Deploy to AWS Amplify
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install AWS Amplify CLI
              run: npm install -g @aws-amplify/cli

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to AWS Amplify
              run: |
                  amplify status
                  amplify push --yes
